### ISSUE TITLE
Implement plugin download

### ISSUE THREAD

**Issue by mathiaszinnen** [mathiaszinnen/open-data-service#16]
Is it possible to create downloadable responses with jsonApi? If so, the JsonApiResponse classes need to be extended with this functionality.
https://github.com/mathiaszinnen/open-data-service/blob/e76a7780630aafc725cedb44fff62d372574deac/server/src/main/java/org/jvalue/ods/rest/v2/PluginApi.java#L111

**Comment by andreas-bauer** [comment]
Please remove PluginAPI endpoint from v2 API
